#!/bin/sh

export TOKEN=`curl --user app:bfbd9f62-02ce-4638-a370-80d45514bd0a localhost:9999/auth/realms/$1/protocol/openid-connect/token -dgrant_type=password -dusername=$2 -dpassword=password -dscope="$3" | jq -r .access_token`
